### PR TITLE
Use cluster name in URIs.

### LINKED ISSUE #1341: Integrate extended ACL
For cluster-specific resource (with schemes `storage`, `image` and `job`) client should use URIs containing the cluster name, e.g. `storage://{clustername}/{username}/{path}` instead of `storage://{username}/{path}`.

Relative URI `storage:{path}` should expand to absolute URI containing the current cluster name and the user name: `storage://{clustername}/{username}/{path}`. Same for `image` and `job` schemes.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Closes #1341.

### CODE REVIEW

**Comment by asvetlov** [comment]
Aha, I see a couple of merge conflicts.
Shoud be easy to fix them.

**Comment by serhiy-storchaka** [comment]
It can be merged after we have enabled support of extended ACL on all services on stage.

**Comment by asvetlov** [comment]
Got you

**Comment by ayushkovskiy** [comment]
Perhaps, this PR will close https://github.com/neuromation/platform-client-python/issues/1404

**Comment by asvetlov** [comment]
Let's merge it!

**Pull request merged**
