### PR TITLE
Implement images and image tags pagination

### LINKED ISSUE #1606: Implement image pagination
https://github.com/neuromation/platform-registry-api/pull/174

https://docs.docker.com/registry/spec/api/#listing-repositories

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Closes #1606.

### CODE REVIEW

**Review by asvetlov — COMMENTED** [review]
Everything is done on the server-side, correct?

**Review by romasku — APPROVED** [review]
Looks good to me, thx for implementing it on client side.

**Comment by serhiy-storchaka** [comment]
I get HTTP error 504 (Gateway Timeout) when set REPOS_PER_PAGE to too small value (2).

**Comment by serhiy-storchaka** [comment]
Ah, and `test_image_tags` still failed because we only implemented pagination for the list of images, not tags.

**Pull request merged**
