### PR TITLE
Improve copying progress.

### LINKED ISSUE #1034: Sorting files being uploaded by progress breaks user's eyes
Issue by @GolovanovSrg 

When copying many files of almost-same size via `neuro cp --progress`, the files are sorted by progress, such that the sorting order changes constantly and the console output flickers, ruining health or the user's eyes. Let's maybe sort files by name?

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
When start copying a directory, output `{uri} ...`.
When finish copying a directory, output `{uri} DONE`.
When update the file line, try to update it inplace if it is visible, without reordering other lines.
When the file line is not visible (a new one or was scrolled up), add it the end.
If the current directory differs from the file parent, output `{parent-uri} ...` before the file line.

Closes #1034.

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Also removed sorting. It does not make sense, as transferring all files and directories starts concurrently.

**Comment by asvetlov** [comment]
pls let me check locally how the PR looks like

**Comment by asvetlov** [comment]
I have the following tree:
```
andrew•projects/neuromation/platform-client-python(storage-progress⚡)» tree demo_folder                     (platform-client-python)  [18:21:22]
demo_folder
├── 2.zip
├── api
│   ├── abc.py
│   ├── client.py
│   ├── config_factory.py
│   ├── config.py
│   ├── core.py
│   ├── images.py
│   ├── __init__.py
│   ├── jobs.py
│   ├── login.py
│   ├── parser.py
│   ├── parsing_utils.py
│   ├── registry.py
│   ├── storage.py
│   ├── url_utils.py
│   ├── users.py
│   └── utils.py
├── FW_RT_AC1200GPlus_300438251610.zip
├── __init__.py
├── py.typed
├── strings
│   ├── __init__.py
│   └── parse.py
└── utils.py

2 directories, 23 files
```
One of `neuro cp` runs shows:
```
andrew•projects/neuromation/platform-client-python(storage-progress⚡)» neuro cp demo_folder storage: -r     (platform-client-python)  [18:18:03]
Copy file:///.../projects/neuromation/platform-client-python/demo_folder => storage://asvetlov/demo_folder
parsing_utils.py 6.8K
storage.py 15.6K
users.py 2.8K
url_utils.py 3.4K
core.py 3.5K
parser.py 1.7K
registry.py 732B
FW_RT_AC1200GPlus_300438251610.zip 15.1M
file:///home/andrew/projects/neuromation/platform-client-python/demo_folder/api DONE
file:///home/andrew/projects/neuromation/platform-client-python/demo_folder DONE
```

Take a look on the tail.
`parser.py` and `registry.py` belong to `demo_folder/api`, `FW_RT_AC1200GPlus_300438251610.zip` belongs to top-level `demo_folder`. I expect pushing a folder before `FW_RT_AC1200GPlus_300438251610.zip`, e.g.
```
...
parser.py 1.7K
registry.py 732B
file:///home/andrew/projects/neuromation/platform-client-python/demo_folder/
FW_RT_AC1200GPlus_300438251610.zip 15.1M
file:///home/andrew/projects/neuromation/platform-client-python/demo_folder/api DONE
...
```
does it make sense?

**Comment by serhiy-storchaka** [comment]
It should be fixed now.

I have changed also the algorithm of dropping lines, so the first line is now always a dir line.

**Pull request merged**
